site_name: Maths docs
site_url: https://maths.0xninja.fr
theme:
  name: material
  language: fr
  icon:
    logo: fontawesome/solid/square-root-variable
  favicon: assets/favicon.jpg
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.expand
    - navigation.instant
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Passer en mode nuit
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Passer en mode jour
  font:
    code: JetBrains Mono

markdown_extensions:
  - toc:
      permalink: '#'
      toc_depth: 3
      slugify: !!python/name:pymdownx.slugs.uslugify_encoded
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - abbr
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.keys

extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://0xninja.fr
    - icon: fontawesome/brands/github
      link: https://github.com/OxNinja
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/0x_Ninja

extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

